minor

diff --git a/bin/jtframe b/bin/jtframe
--- a/bin/jtframe
+++ b/bin/jtframe
@@ -1,6 +1,11 @@
 #!/bin/bash
 POCKET=
 
+if [ -z "$JTFRAME" ]; then
+    echo "Missing JTFRAME environment variable definition"
+    exit 1
+fi
+
 if [ ! -e $JTFRAME/src/jtframe ]; then
     if [ -e $JTFRAME/target/pocket/pocket.go ]; then
         ln -srf $JTFRAME/target/pocket/pocket.go $JTFRAME/src/mra/pocket.go
